development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: postfolio_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: portfolio_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: portfolio
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432