# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e431adf3b71ba8235e07d0898d1de757f049d02d0928dd2f52bcc13f5e31dd52128c97c046f0c7afea42866195bb471be2a2cfca63b71495e480f72e4d682790

test:
  secret_key_base: d0d06ad640723051c2d835f1938817aecf89db67d406ed7da5d27cc04abc879fbc7ebc053555bf37214ce6497967f9d3950d8722ad197cd6e20bd7df27c836f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
